=== andytanoko/4.2.x_integration/PDIPBaseServices/DocService/data/BPSS1.01.dtd
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by christopher ferris (sun microsystems, inc) -->
<!-- =============================================================== -->
<!--  Editor:   Kurt Kanaskie (Lucent Technologies)                  -->
<!--  Version:  Version 1.0                                          -->
<!--  Updated:  2001-05-10                                           -->
<!--                                                                 -->
<!--  Public Identifier:                                             -->
<!--            "-//ebXML//DTD Process Specification ver 1.0//EN"    -->
<!--                                                                 -->
<!--  Purpose:                                                       -->
<!--     The ebXML Specification DTD provides a standard             -->
<!--     framework by which business systems may be                  -->
<!--     configured to support execution of business                 -->
<!--     transactions.  It is based upon prior UN/CEFACT             -->
<!--     work, specifically the metamodel behind the                 -->
<!--     UN/CEFACT Unified Modeling Methodology (UMM) defined        -->
<!--     in the N090R9.1  specification.                                   -->
<!--                                                                 -->
<!--     The Specification Schema supports the specification         -->
<!--     of Business Transactions and the choreography of            -->
<!--     Business Transactions into Business Collaborations.         -->
<!--                                                                 -->
<!--  Notes:                                                         -->
<!--     time periods are represented using ISO 8601 format          -->
<!--     (e.g. P2D for 2 Days, P2H30M for 2 Hours 30 Minutes         -->
<!--                                                                 -->
<!--     Naming and reference is based on convention that an         -->
<!--     Element with a name attribute (e.g. AuthorizedRole)         -->
<!--     is refernced by an attribute in another element with        -->
<!--     the name in lowerCamelCase (e.g. authorizedRole).           -->
<!--                                                                 -->
<!--     fromBusinessState and toBusinessState refer to the          -->
<!--     the names of a BusinessTransactionActivity,                 -->
<!--     CollaborationActivity, Fork, and Join, all are targets for  -->
<!--     from/to in Transition. This deviates from the normal        -->
<!--     convention of lowerCamelCase attribute name                 -->
<!--     BusinessState is used as a generic term for:                -->
<!--     Fork, Join, Success, Failure                                -->
<!--                                                                 -->
<!-- Constraints:                                                    -->
<!--     - attributes location, logicalModel, pattern, specification -->
<!--	   uri, are of type xsd:anyURI                               -->
<!--     - attributes timeTo* are of type xsd:duration               -->
<!--       isSuccess is an expression (e.g. XPath) that results      -->
<!--       in a boolean true or false based on document name or      -->
<!--       document content.                                         -->
<!--                                                                 -->
<!-- =============================================================== -->
<!ELEMENT ProcessSpecification (Documentation*, SubstitutionSet*, (Include* | BusinessDocument* | ProcessSpecification* | Package | BinaryCollaboration | BusinessTransaction | MultiPartyCollaboration)*)>
<!ATTLIST ProcessSpecification
	name ID #REQUIRED
	uuid CDATA #REQUIRED
	version CDATA #REQUIRED
>
<!ELEMENT Documentation (#PCDATA)>
<!ATTLIST Documentation
	uri CDATA #IMPLIED
>
<!ELEMENT Include (Documentation*)>
<!ATTLIST Include
	name CDATA #REQUIRED
	uuid CDATA #REQUIRED
	uri CDATA #REQUIRED
	version CDATA #REQUIRED
>
<!ELEMENT BusinessDocument (ConditionExpression?, Documentation*)>
<!ATTLIST BusinessDocument
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	specificationLocation CDATA #IMPLIED
	specificationElement CDATA #IMPLIED
>
<!ELEMENT ConditionExpression (Documentation*)>
<!ATTLIST ConditionExpression
	expressionLanguage CDATA #IMPLIED
	expression CDATA #IMPLIED
>
<!ELEMENT SubstitutionSet (DocumentSubstitution | AttributeSubstitution | Documentation)*>
<!ATTLIST SubstitutionSet
	name CDATA #IMPLIED
	nameId IDREF #IMPLIED
	applyToScope CDATA #IMPLIED
>
<!ELEMENT DocumentSubstitution (Documentation*)>
<!ATTLIST DocumentSubstitution
	originalBusinessDocument CDATA #IMPLIED
	originalBusinessDocumentID IDREF #IMPLIED
	substituteBusinessDocument CDATA #IMPLIED
	substituteBusinessDocumentId IDREF #IMPLIED
>
<!ELEMENT AttributeSubstitution (Documentation*)>
<!ATTLIST AttributeSubstitution
	attributeName CDATA #IMPLIED
	value CDATA #IMPLIED
>
<!ELEMENT Package (Documentation*, (Package | BinaryCollaboration | BusinessTransaction | MultiPartyCollaboration)*)>
<!ATTLIST Package
	name CDATA #REQUIRED
	nameID ID #IMPLIED
>
<!ELEMENT BinaryCollaboration (Documentation*, InitiatingRole, RespondingRole, (Documentation* | Start | Transition | Success | Failure | BusinessTransactionActivity | CollaborationActivity | Fork | Join)*)>
<!ATTLIST BinaryCollaboration
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	pattern CDATA #IMPLIED
	beginsWhen CDATA #IMPLIED
	endsWhen CDATA #IMPLIED
	preCondition CDATA #IMPLIED
	postCondition CDATA #IMPLIED
	timeToPerform CDATA #IMPLIED
>
<!ELEMENT MultiPartyCollaboration (Documentation*, BusinessPartnerRole*)>
<!ATTLIST MultiPartyCollaboration
	name CDATA #REQUIRED
	nameID ID #IMPLIED
>
<!ELEMENT InitiatingRole (Documentation*)>
<!ATTLIST InitiatingRole
	name CDATA #REQUIRED
	nameID ID #IMPLIED
>
<!ELEMENT RespondingRole (Documentation*)>
<!ATTLIST RespondingRole
	name CDATA #REQUIRED
	nameID ID #IMPLIED
>
<!-- A BusinessState is one of Start, Success, Failure, Fork, Join, BusinessTransactionActivity or CollaborationActivity -->
<!-- fromBusinessState and toBusinessState are fully qualified using XPath -->
<!ELEMENT Transition (ConditionExpression?, Documentation*)>
<!ATTLIST Transition
	onInitiation (true | false) "false"
	fromBusinessState CDATA #IMPLIED
	fromBusinessStateIDRef IDREF #IMPLIED
	toBusinessState CDATA #IMPLIED
	toBusinessStateIDRef IDREF #IMPLIED
	conditionGuard (Success | BusinessFailure | TechnicalFailure | AnyFailure) #IMPLIED
>
<!-- Start is a special type of Transition in that it only has a destination -->
<!ELEMENT Start (Documentation*)>
<!ATTLIST Start
	toBusinessState CDATA #REQUIRED
	toBusinessStateIDRef IDREF #IMPLIED
>
<!-- Success is a special type of Transition in that it only has a origination -->
<!ELEMENT Success (ConditionExpression?, Documentation*)>
<!ATTLIST Success
	fromBusinessState CDATA #REQUIRED
	fromBusinessStateIDRef IDREF #IMPLIED
	conditionGuard (Success | BusinessFailure | TechnicalFailure | AnyFailure) #IMPLIED
>
<!-- Failure is a special type of Transition in that it only has a origination -->
<!ELEMENT Failure (ConditionExpression?, Documentation*)>
<!ATTLIST Failure
	fromBusinessState CDATA #REQUIRED
	fromBusinessStateIDRef IDREF #IMPLIED
	conditionGuard (Success | BusinessFailure | TechnicalFailure | AnyFailure) #IMPLIED
>
<!-- Fork is a special type of BusinessState that can be transitioned to -->
<!ELEMENT Fork (Documentation*)>
<!ATTLIST Fork
	name CDATA #REQUIRED
	nameID ID #IMPLIED
>
<!-- Join is a special type of BusinessState that can be transitioned to -->
<!ELEMENT Join (Documentation*)>
<!ATTLIST Join
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	waitForAll (true | false) "true"
>
<!-- fromAuthorizedRole and toAuthorizedRole are fully qualified using XPath -->
<!-- BusinessTransactionActivity is a BusinessState that can be transitioned to -->
<!ELEMENT BusinessTransactionActivity (Documentation*)>
<!ATTLIST BusinessTransactionActivity
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	businessTransaction CDATA #REQUIRED
	businessTransactionIDRef IDREF #IMPLIED
	fromAuthorizedRole CDATA #REQUIRED
	fromAuthorizedRoleIDRef IDREF #IMPLIED
	toAuthorizedRole CDATA #REQUIRED
	toAuthorizedRoleIDRef IDREF #IMPLIED
	isConcurrent (true | false) "true"
	isLegallyBinding (true | false) "true"
	timeToPerform CDATA #IMPLIED
>
<!-- fromAuthorizedRole and toAuthorizedRole are fully qualified using XPath -->
<!-- CollaborationActivity is a BusinessState that can be transitioned to -->
<!ELEMENT CollaborationActivity (Documentation*)>
<!ATTLIST CollaborationActivity
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	fromAuthorizedRole CDATA #REQUIRED
	fromAuthorizedRoleIDRef IDREF #IMPLIED
	toAuthorizedRole CDATA #REQUIRED
	toAuthorizedRoleIDRef IDREF #IMPLIED
	binaryCollaboration CDATA #REQUIRED
	binaryCollaborationIDRef IDREF #IMPLIED
>
<!ELEMENT BusinessTransaction (Documentation*, RequestingBusinessActivity, RespondingBusinessActivity)>
<!ATTLIST BusinessTransaction
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	pattern CDATA #IMPLIED
	beginsWhen CDATA #IMPLIED
	endsWhen CDATA #IMPLIED
	isGuaranteedDeliveryRequired (true | false) "false"
	preCondition CDATA #IMPLIED
	postCondition CDATA #IMPLIED
>
<!ELEMENT RequestingBusinessActivity (Documentation*, DocumentEnvelope)>
<!ATTLIST RequestingBusinessActivity
	name CDATA #IMPLIED
	nameID ID #IMPLIED
	isAuthorizationRequired (true | false) "false"
	isIntelligibleCheckRequired (true | false) "false"
	isNonRepudiationReceiptRequired (true | false) "false"
	isNonRepudiationRequired (true | false) "false"
	timeToAcknowledgeAcceptance CDATA #IMPLIED
	timeToAcknowledgeReceipt CDATA #IMPLIED
>
<!ELEMENT RespondingBusinessActivity (Documentation*, DocumentEnvelope*)>
<!ATTLIST RespondingBusinessActivity
	name CDATA #IMPLIED
	nameID ID #IMPLIED
	isAuthorizationRequired (true | false) "false"
	isIntelligibleCheckRequired (true | false) "false"
	isNonRepudiationReceiptRequired (true | false) "false"
	isNonRepudiationRequired (true | false) "false"
	timeToAcknowledgeReceipt CDATA #IMPLIED
>
<!ELEMENT DocumentEnvelope (Documentation*, Attachment*)>
<!ATTLIST DocumentEnvelope
	businessDocument CDATA #REQUIRED
	businessDocumentIDRef IDREF #IMPLIED
	isPositiveResponse (true | false) "false"
	isAuthenticated (true | false) "false"
	isConfidential (true | false) "false"
	isTamperProof (true | false) "false"
>
<!ELEMENT Attachment (Documentation*)>
<!ATTLIST Attachment
	name CDATA #REQUIRED
	nameID ID #IMPLIED
	businessDocument CDATA #IMPLIED
	businessDocumentIDRef IDREF #IMPLIED
	mimeType CDATA #REQUIRED
	specification CDATA #IMPLIED
	version CDATA #IMPLIED
	isAuthenticated (true | false) "false"
	isConfidential (true | false) "false"
	isTamperProof (true | false) "false"
>
<!ELEMENT BusinessPartnerRole (Documentation*, Performs*, Transition*)>
<!ATTLIST BusinessPartnerRole
	name CDATA #REQUIRED
	nameID ID #IMPLIED
>
<!-- authorizedRole is fully qualified using XPath -->
<!ELEMENT Performs (Documentation*)>
<!ATTLIST Performs
	initiatingRole CDATA #IMPLIED
	inititiatingRoleIDRef IDREF #IMPLIED
	respondingRole CDATA #IMPLIED
	respondingRoleIDRef IDREF #IMPLIED
>

=== andytanoko/4.2.x_integration/PDIPAppServices/Deploy/data/ebBPSS.xml
<!-- edited by Kurt Kanaskie (Lucent Technologies) -->
<!-- Notes from Kurt Kanaskie on 2001-04-17
     Differences from 099 DTD:
	binaryCollaboration attribute in Performs
	fromBinaryCollaboration attribute in Transition
	toBinaryCollaboration attribute in Transition
     Differences from original:
	guard instead of guardExpression
     See EBXMLSpecification_2001_04_23.dtd for other changes
-->
<!DOCTYPE ProcessSpecification SYSTEM "BPSS1.01.dtd">
<ProcessSpecification name="Simple" version="1.1" uuid="[1234-5678-901234]">
	<!-- Business Documents -->
		<BusinessDocument name="Catalog Request"/>
		<BusinessDocument name="Catalog"/>
		<BusinessDocument name="Purchase Order"/>
		<BusinessDocument name="PO Acknowledgement"/>
		<BusinessDocument name="Credit Request"/>
		<BusinessDocument name="Credit Confirm"/>
		<BusinessDocument name="ASN"/>
		<BusinessDocument name="CreditAdvice"/>
		<BusinessDocument name="DebitAdvice"/>
		<BusinessDocument name="Invoice"/>
		<BusinessDocument name="Payment"/>
		<BusinessDocument name="Inventory Report Request"/>
		<BusinessDocument name="Inventory Report"/>
		<BusinessDocument name="Inventory Report"/>
	<Package name="Ordering">
		<!-- First the overall MultiParty Collaboration -->
		<MultiPartyCollaboration name="DropShip">
			<BusinessPartnerRole name="Customer">
				<Performs initiatingRole="requestor"/>
				<Performs initiatingRole="buyer"/>
				<Transition fromBusinessState="Catalog Request" toBusinessState="Create Order"/>
			</BusinessPartnerRole>
			<BusinessPartnerRole name="Retailer">
				<Performs respondingRole="provider"/>
				<Performs respondingRole="seller"/>
				<Performs initiatingRole="Creditor"/>
				<Performs initiatingRole="buyer"/>
				<Performs initiatingRole="Payee"/>
				<Performs respondingRole="Payor"/>
				<Performs initiatingRole="requestor"/>
				<Transition fromBusinessState="Create Order" toBusinessState="Check Credit"/>
				<Transition fromBusinessState="Check Credit" toBusinessState="Create Order"/>
			</BusinessPartnerRole>
			<BusinessPartnerRole name="DropShip Vendor">
				<Performs respondingRole="seller"/>
				<Performs initiatingRole="payee"/>
				<Performs respondingRole="provider"/>
			</BusinessPartnerRole>
			<BusinessPartnerRole name="Credit Authority">
				<Performs respondingRole="credit service"/>
				<Performs respondingRole="payor"/>
			</BusinessPartnerRole>
		</MultiPartyCollaboration>
		<!-- Now the Binary Collaborations -->
		<BinaryCollaboration name="Request Catalog">
			<InitiatingRole name="requestor"/>
			<RespondingRole name="provider"/>
			<BusinessTransactionActivity name="Catalog Request" businessTransaction="Catalog Request" fromAuthorizedRole="requestor" toAuthorizedRole="provider"/>
		</BinaryCollaboration>
		<BinaryCollaboration name="Firm Order" timeToPerform="P2D">
			<Documentation>timeToPerform = Period: 2 days from start of transaction</Documentation>
			<InitiatingRole name="buyer"/>
			<RespondingRole name="seller"/>
			<BusinessTransactionActivity name="Create Order" businessTransaction="Create Order" fromAuthorizedRole="buyer" toAuthorizedRole="seller"/>
		</BinaryCollaboration>
		<BinaryCollaboration name="Product Fulfillment" timeToPerform="P5D">
			<Documentation>timeToPerform = Period: 5 days from start of transaction</Documentation>
			<InitiatingRole name="buyer"/>
			<RespondingRole name="seller"/>
			<BusinessTransactionActivity name="Create Order" businessTransaction="Create Order" fromAuthorizedRole="buyer" toAuthorizedRole="seller"/>
			<BusinessTransactionActivity name="Notify shipment" businessTransaction="Notify of advance shipment" fromAuthorizedRole="buyer" toAuthorizedRole="seller"/>
			<Start toBusinessState="Create Order"/>
			<Transition fromBusinessState="Create Order" toBusinessState="Notify shipment"/>
			<Success fromBusinessState="Notify shipment" conditionGuard="Success"/>
			<Failure fromBusinessState="Notify shipment" conditionGuard="BusinessFailure"/>
		</BinaryCollaboration>
		<BinaryCollaboration name="Inventory Status">
			<InitiatingRole name="requestor"/>
			<RespondingRole name="provider"/>
			<BusinessTransactionActivity name="Inventory Report Request" businessTransaction="Inventory Report Request" fromAuthorizedRole="requestor" toAuthorizedRole="provider"/>
			<BusinessTransactionActivity name="Inventory Report" businessTransaction="Inventory Report" fromAuthorizedRole="provider" toAuthorizedRole="requestor"/>
		</BinaryCollaboration>
		<BinaryCollaboration name="Credit Inquiry">
			<InitiatingRole name="creditor"/>
			<RespondingRole name="credit service"/>
			<BusinessTransactionActivity name="Check Credit" businessTransaction="Check Credit" fromAuthorizedRole="creditor" toAuthorizedRole="credit service"/>
		</BinaryCollaboration>
		<BinaryCollaboration name="Credit Payment">
			<InitiatingRole name="payee"/>
			<RespondingRole name="payor"/>
			<BusinessTransactionActivity name="Process Credit Payment" businessTransaction="Process Credit Payment" fromAuthorizedRole="payee" toAuthorizedRole="payor"/>
		</BinaryCollaboration>
		<!-- A compound BinaryCollaboration for illustration purposes-->
		<BinaryCollaboration name="Credit Charge">
			<InitiatingRole name="charger"/>
			<RespondingRole name="credit service"/>
			<CollaborationActivity name="Credit Inquiry" binaryCollaboration="Credit Inquiry" fromAuthorizedRole="charger" toAuthorizedRole="credit service"/>
			<CollaborationActivity name="Credit Payment" binaryCollaboration="Credit Payment" fromAuthorizedRole="charger" toAuthorizedRole="payor"/>
			<Transition fromBusinessState="Credit Inquiry" toBusinessState="Credit Payment"/>
		</BinaryCollaboration>
		<BinaryCollaboration name="Fulfillment Payment">
			<InitiatingRole name="payee"/>
			<RespondingRole name="payor"/>
			<BusinessTransactionActivity name="Process Payment" businessTransaction="Process Payment" fromAuthorizedRole="payee" toAuthorizedRole="payor"/>
		</BinaryCollaboration>
		<!-- Here are all the Business Transactions needed -->
		<BusinessTransaction name="Catalog Request">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Catalog Request"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Catalog"/>
			</RespondingBusinessActivity>
		</BusinessTransaction>
		<BusinessTransaction name="Create Order">
			<RequestingBusinessActivity name="" isNonRepudiationRequired="true" timeToAcknowledgeReceipt="P2D" timeToAcknowledgeAcceptance="P3D">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Purchase Order"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="" isNonRepudiationRequired="true" timeToAcknowledgeReceipt="P5D">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="PO Acknowledgement"/>
			</RespondingBusinessActivity>
		</BusinessTransaction>
		<BusinessTransaction name="Check Credit ">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Credit Request"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Credit Confirm"/>
			</RespondingBusinessActivity>
		</BusinessTransaction>
		<BusinessTransaction name="Notify of advance shipment">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="ASN"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="" timeToAcknowledgeReceipt="P2D"/>
		</BusinessTransaction>
		<BusinessTransaction name="Process Credit Payment">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="CreditAdvice"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="DebitAdvice"/>
			</RespondingBusinessActivity>
		</BusinessTransaction>
		<BusinessTransaction name="Process Payment">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Invoice"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Payment"/>
			</RespondingBusinessActivity>
		</BusinessTransaction>
		<BusinessTransaction name="Request Inventory Report">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Inventory Report Request"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Inventory Report"/>
			</RespondingBusinessActivity>
		</BusinessTransaction>
		<BusinessTransaction name="Inventory Report">
			<RequestingBusinessActivity name="">
				<DocumentEnvelope isPositiveResponse="true" businessDocument="Inventory Report"/>
			</RequestingBusinessActivity>
			<RespondingBusinessActivity name=""/>
		</BusinessTransaction>
	</Package>
</ProcessSpecification>
